### ISSUE TITLE
Does not work for a private repo

### ISSUE THREAD

**Issue by GlennWSo** [mloskot/github-label-maker#7]
## steps to reproduce

gh_label_maker -o a-owner -r a-private-repo -d dump.json

## Error msg
Traceback (most recent call last):
  File "/home/gws/projects/cerinvent-scale/.venv/bin/gh_label_maker", line 8, in <module>
    sys.exit(run())
  File "/home/gws/projects/cerinvent-scale/.venv/lib/python3.10/site-packages/gh_label_maker/cli.py", line 43, in run
    hub = glm.GithubLabelMaker(args.token, args.owner, args.repository, verbose=args.verbose)
  File "/home/gws/projects/cerinvent-scale/.venv/lib/python3.10/site-packages/gh_label_maker/glm.py", line 34, in __init__
    self._repo = owner.get_repo(github_repo_name)
  File "/home/gws/projects/cerinvent-scale/.venv/lib/python3.10/site-packages/github/AuthenticatedUser.py", line 1069, in get_repo
    headers, data = self._requester.requestJsonAndCheck(
  File "/home/gws/projects/cerinvent-scale/.venv/lib/python3.10/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/gws/projects/cerinvent-scale/.venv/lib/python3.10/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-repository"}

**Comment by mloskot** [comment]
Interesting. I believe I did use it with private repo, but it was long time ago
